### ISSUE TITLE
Couldn't compile on Linux Mint 21.2 (base: Ubuntu 22.04 jammy)

### ISSUE THREAD

**Issue by KarmyDev** [3ddelano/epic-online-services-godot#16]
Got error while compiling from the source - main
```cpp
In file included from src/auth_interface.cpp:1:
src/ieos.h:261:10: error: extra qualification 'godot::IEOS::' on member 'ui_interface_get_friends_exclusive_input' [-fpermissive]
  261 |     bool IEOS::ui_interface_get_friends_exclusive_input(Ref<RefCounted> options);
      |          ^~~~
src/ieos.h:262:10: error: extra qualification 'godot::IEOS::' on member 'ui_interface_show_block_player' [-fpermissive]
  262 |     void IEOS::ui_interface_show_block_player(Ref<RefCounted> options);
      |          ^~~~
src/ieos.h:263:10: error: extra qualification 'godot::IEOS::' on member 'ui_interface_show_report_player' [-fpermissive]
  263 |     void IEOS::ui_interface_show_report_player(Ref<RefCounted> options);
      |          ^~~~
src/ieos.h:264:9: error: extra qualification 'godot::IEOS::' on member 'ui_interface_pause_social_overlay' [-fpermissive]
  264 |     int IEOS::ui_interface_pause_social_overlay(Ref<RefCounted> options);
      |         ^~~~
src/ieos.h:265:10: error: extra qualification 'godot::IEOS::' on member 'ui_interface_is_social_overlay_paused' [-fpermissive]
  265 |     bool IEOS::ui_interface_is_social_overlay_paused(Ref<RefCounted> options);
      |          ^~~~
In file included from src/achievements_interface.cpp:1:
src/ieos.h:261:10: error: extra qualification 'godot::IEOS::' on member 'ui_interface_get_friends_exclusive_input' [-fpermissive]
  261 |     bool IEOS::ui_interface_get_friends_exclusive_input(Ref<RefCounted> options);
      |          ^~~~
src/ieos.h:262:10: error: extra qualification 'godot::IEOS::' on member 'ui_interface_show_block_player' [-fpermissive]
  262 |     void IEOS::ui_interface_show_block_player(Ref<RefCounted> options);
      |          ^~~~
src/ieos.h:263:10: error: extra qualification 'godot::IEOS::' on member 'ui_interface_show_report_player' [-fpermissive]
  263 |     void IEOS::ui_interface_show_report_player(Ref<RefCounted> options);
      |          ^~~~
src/ieos.h:264:9: error: extra qualification 'godot::IEOS::' on member 'ui_interface_pause_social_overlay' [-fpermissive]
  264 |     int IEOS::ui_interface_pause_social_overlay(Ref<RefCounted> options);
      |         ^~~~
src/ieos.h:265:10: error: extra qualification 'godot::IEOS::' on member 'ui_interface_is_social_overlay_paused' [-fpermissive]
  265 |     bool IEOS::ui_interface_is_social_overlay_paused(Ref<RefCounted> options);
      |          ^~~~
```

And after a long wall of text:

```cpp
es/xr_positional_tracker.linux.template_debug.dev.x86_64.o godot-cpp/gen/src/classes/xr_server.linux.template_debug.dev.x86_64.o godot-cpp/gen/src/classes/zip_packer.linux.template_debug.dev.x86_64.o godot-cpp/gen/src/classes/zip_reader.linux.template_debug.dev.x86_64.o godot-cpp/gen/src/variant/utility_functions.linux.template_debug.dev.x86_64.o
scons: *** [src/auth_interface.os] Error 1
scons: *** [src/achievements_interface.os] Error 1
In file included from src/connect_interface.cpp:1:
src/ieos.h:261:10: error: extra qualification 'godot::IEOS::' on member 'ui_interface_get_friends_exclusive_input' [-fpermissive]
  261 |     bool IEOS::ui_interface_get_friends_exclusive_input(Ref<RefCounted> options);
      |          ^~~~
src/ieos.h:262:10: error: extra qualification 'godot::IEOS::' on member 'ui_interface_show_block_player' [-fpermissive]
  262 |     void IEOS::ui_interface_show_block_player(Ref<RefCounted> options);
      |          ^~~~
src/ieos.h:263:10: error: extra qualification 'godot::IEOS::' on member 'ui_interface_show_report_player' [-fpermissive]
  263 |     void IEOS::ui_interface_show_report_player(Ref<RefCounted> options);
      |          ^~~~
src/ieos.h:264:9: error: extra qualification 'godot::IEOS::' on member 'ui_interface_pause_social_overlay' [-fpermissive]
  264 |     int IEOS::ui_interface_pause_social_overlay(Ref<RefCounted> options);
      |         ^~~~
src/ieos.h:265:10: error: extra qualification 'godot::IEOS::' on member 'ui_interface_is_social_overlay_paused' [-fpermissive]
  265 |     bool IEOS::ui_interface_is_social_overlay_paused(Ref<RefCounted> options);
      |          ^~~~
scons: *** [src/connect_interface.os] Error 1
ranlib godot-cpp/bin/libgodot-cpp.linux.template_debug.dev.x86_64.a
scons: building terminated because of errors.

```

Did everything that was told in the Readme

**Comment by LowFire** [comment]
I had the same problem trying to compile on linux using gcc. It won't be too hard to fix, just need to remove the `IEOS::` at the beginning of each of those functions and it should be all good.

**Comment by 3ddelano** [comment]
There were some compilation errors on Linux, such as use of strncpy_s() as well as some implicit type casts. It has been fixed in commit https://github.com/3ddelano/epic-online-services-godot/commit/866dfd8412d45d6f1f0d481a1bd9933f24bd223f
